name: Scheduled Daily Build

on:
  schedule:
    # Run every day at 12:00 PM UTC
    # Reference: https://crontab.guru/
     - cron: '*/5 * * * *'
    #- cron: '0 12 * * *'
    #- cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest # Specify the runner environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checkout your repository code
      - name: Set up Python
        uses: actions/setup-python@v5 # Set up a Python environment using recent version
        with:
          python-version: '3.10' # Specify your desired Python version
          cache: 'pip'  # Optional: Caches dependencies for faster subsequent runs
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run Python pipelines
        working-directory: ./pipelines # Set the working directory
        run: |
          python population_by_country_monthly_etl.py 
