name: Scheduled Daily Build

on:
  schedule:
    # Run every day at 12:00 PM UTC
    # Reference: https://crontab.guru/
    # - cron: '*/5 * * * *'
    #- cron: '0 12 * * *'
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest # Specify the runner environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checkout your repository code
      - name: Set up Python
        uses: actions/setup-python@v5 # Set up a Python environment using recent version
        with:
          python-version: '3.x' # Specify your desired Python version
      - name: Run a scheduled Python script
        working-directory: ./scripts # Set the working directory
        run: |
          python test_script.py # Execute your Python script